#!/bin/bash
#requested_object=$1
xterm -e "roscore; bash" &
sleep 3;
xterm -e "roslaunch realsense2_camera rs_rgbd.launch; bash" &
sleep 3;
xterm -e "roslaunch darknet_ros yolo_v3.launch" &
sleep 5;
xterm -e "roslaunch kobuki_node minimal.launch; bash" &
sleep 2;
xterm -e "roslaunch rplidar_ros rplidar.launch; bash" &
sleep 2;
xterm -e "roslaunch laser_values lazer.launch; bash" &
sleep 2;

xterm -e "python cam_node.py; bash" &
xterm -e "rosrun point_cloud point_cloud; bash" &
xterm -e "python controller.py; bash" &
